# version: '3'
# services:
#   spark-master:
#     image: bde2020/spark-master:3.3.0-hadoop3.3
#     container_name: spark-master
#     ports:
#       - "8080:8080"
#       - "7077:7077"
#     environment:
#       - INIT_DAEMON_STEP=setup_spark
#   spark-worker-1:
#     image: bde2020/spark-worker:3.3.0-hadoop3.3
#     container_name: spark-worker-1
#     depends_on:
#       - spark-master
#     ports:
#       - "8081:8081"
#     environment:
#       - "SPARK_MASTER=spark://spark-master:7077"

# spark-submit --master spark://spark-master:7077 /spark/examples/src/main/python/pi.py
# ping spark-master
# export SPARK_HOME=/spark
# export PATH=$SPARK_HOME/bin:$PATH
# export JAVA_HOME=/usr/lib/jvm/java-8-openjdk
# export PATH=$JAVA_HOME/bin:$PATH
# echo $SPARK_HOME
# echo $JAVA_HOME
# echo $PATH
# docker exec -it spark-master spark/bin/spark-submit --version

version: '3'
services:
  spark-master:
    image: bde2020/spark-master:3.2.1-hadoop3.2
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark

  spark-worker-1:
    image: bde2020/spark-worker:3.2.1-hadoop3.2
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

  spark-worker-2:
    image: bde2020/spark-worker:3.2.1-hadoop3.2
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

  spark-worker-3:
    image: bde2020/spark-worker:3.2.1-hadoop3.2
    container_name: spark-worker-3
    depends_on:
      - spark-master
    ports:
      - "8083:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

  spark-worker-4:
    image: bde2020/spark-worker:3.2.1-hadoop3.2
    container_name: spark-worker-4
    depends_on:
      - spark-master
    ports:
      - "8084:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

  spark-worker-5:
    image: bde2020/spark-worker:3.2.1-hadoop3.2
    container_name: spark-worker-5
    depends_on:
      - spark-master
    ports:
      - "8085:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
